<<<<<<< .mine
package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProtocol<M extends BaseProtocol<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setServerPact(java.lang.String serverPact) {
		set("server_pact", serverPact);
	}

	public java.lang.String getServerPact() {
		return get("server_pact");
	}

	public void setPrivacy(java.lang.String privacy) {
		set("privacy", privacy);
	}

	public java.lang.String getPrivacy() {
		return get("privacy");
	}

	public void setPlay(java.lang.String play) {
		set("play", play);
	}

	public java.lang.String getPlay() {
		return get("play");
	}

	public void setNotice(java.lang.String notice) {
		set("notice", notice);
	}

	public java.lang.String getNotice() {
		return get("notice");
	}

	public void setOneBuddy(java.lang.String oneBuddy) {
		set("one_buddy", oneBuddy);
	}

	public java.lang.String getOneBuddy() {
		return get("one_buddy");
	}

	public void setTwoBuddy(java.lang.String twoBuddy) {
		set("two_buddy", twoBuddy);
	}

	public java.lang.String getTwoBuddy() {
		return get("two_buddy");
	}

	public void setThreeBuddy(java.lang.String threeBuddy) {
		set("three_buddy", threeBuddy);
	}

	public java.lang.String getThreeBuddy() {
		return get("three_buddy");
	}

	public void setMapAlce(java.lang.String mapAlce) {
		set("map_alce", mapAlce);
	}

	public java.lang.String getMapAlce() {
		return get("map_alce");
	}

	public void setMapMe(java.lang.String mapMe) {
		set("map_me", mapMe);
	}

	public java.lang.String getMapMe() {
		return get("map_me");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setImgLastTime(java.lang.Integer imgLastTime) {
		set("img_last_time", imgLastTime);
	}

	public java.lang.Integer getImgLastTime() {
		return get("img_last_time");
	}

}
=======
package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProtocol<M extends BaseProtocol<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setServerPact(java.lang.String serverPact) {
		set("server_pact", serverPact);
	}

	public java.lang.String getServerPact() {
		return get("server_pact");
	}

	public void setPrivacy(java.lang.String privacy) {
		set("privacy", privacy);
	}

	public java.lang.String getPrivacy() {
		return get("privacy");
	}

	public void setPlay(java.lang.String play) {
		set("play", play);
	}

	public java.lang.String getPlay() {
		return get("play");
	}

	public void setNotice(java.lang.String notice) {
		set("notice", notice);
	}

	public java.lang.String getNotice() {
		return get("notice");
	}

	public void setOneBuddy(java.lang.String oneBuddy) {
		set("one_buddy", oneBuddy);
	}

	public java.lang.String getOneBuddy() {
		return get("one_buddy");
	}

	public void setTwoBuddy(java.lang.String twoBuddy) {
		set("two_buddy", twoBuddy);
	}

	public java.lang.String getTwoBuddy() {
		return get("two_buddy");
	}

	public void setThreeBuddy(java.lang.String threeBuddy) {
		set("three_buddy", threeBuddy);
	}

	public java.lang.String getThreeBuddy() {
		return get("three_buddy");
	}

	public void setMapAlce(java.lang.String mapAlce) {
		set("map_alce", mapAlce);
	}

	public java.lang.String getMapAlce() {
		return get("map_alce");
	}

	public void setMapMe(java.lang.String mapMe) {
		set("map_me", mapMe);
	}

	public java.lang.String getMapMe() {
		return get("map_me");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setImgLastTime(java.lang.Integer imgLastTime) {
		set("img_last_time", imgLastTime);
	}

	public java.lang.Integer getImgLastTime() {
		return get("img_last_time");
	}

	public void setPlayTitle(java.lang.String playTitle) {
		set("play_title", playTitle);
	}

	public java.lang.String getPlayTitle() {
		return get("play_title");
	}

	public void setPlayText(java.lang.String playText) {
		set("play_text", playText);
	}

	public java.lang.String getPlayText() {
		return get("play_text");
	}

}
>>>>>>> .r2112
