package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFileExt<M extends BaseFileExt<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setObjId(java.lang.String objId) {
		set("obj_id", objId);
	}

	public java.lang.String getObjId() {
		return get("obj_id");
	}

	public void setExtName(java.lang.String extName) {
		set("ext_name", extName);
	}

	public java.lang.String getExtName() {
		return get("ext_name");
	}

	public void setExtExt(java.lang.String extExt) {
		set("ext_ext", extExt);
	}

	public java.lang.String getExtExt() {
		return get("ext_ext");
	}

	public void setExtType(java.lang.String extType) {
		set("ext_type", extType);
	}

	public java.lang.String getExtType() {
		return get("ext_type");
	}

	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

}
