package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderRecord<M extends BaseOrderRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setClubId(java.lang.String clubId) {
		set("club_id", clubId);
	}

	public java.lang.String getClubId() {
		return get("club_id");
	}

	public void setOrderNo(java.lang.Long orderNo) {
		set("order_no", orderNo);
	}

	public java.lang.Long getOrderNo() {
		return get("order_no");
	}

	public void setCorpsId(java.lang.String corpsId) {
		set("corps_id", corpsId);
	}

	public java.lang.String getCorpsId() {
		return get("corps_id");
	}

	public void setParticipantsNumber(java.lang.Integer participantsNumber) {
		set("participants_number", participantsNumber);
	}

	public java.lang.Integer getParticipantsNumber() {
		return get("participants_number");
	}

	public void setFeeTotal(java.math.BigDecimal feeTotal) {
		set("fee_total", feeTotal);
	}

	public java.math.BigDecimal getFeeTotal() {
		return get("fee_total");
	}

	public void setFeeCash(java.math.BigDecimal feeCash) {
		set("fee_cash", feeCash);
	}

	public java.math.BigDecimal getFeeCash() {
		return get("fee_cash");
	}

	public void setFeeGold(java.math.BigDecimal feeGold) {
		set("fee_gold", feeGold);
	}

	public java.math.BigDecimal getFeeGold() {
		return get("fee_gold");
	}

	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}

	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	public void setAccountId(java.lang.String accountId) {
		set("account_id", accountId);
	}

	public java.lang.String getAccountId() {
		return get("account_id");
	}

	public void setAccountStatus(java.lang.String accountStatus) {
		set("account_status", accountStatus);
	}

	public java.lang.String getAccountStatus() {
		return get("account_status");
	}

	public void setOrderRebate(java.math.BigDecimal orderRebate) {
		set("order_rebate", orderRebate);
	}

	public java.math.BigDecimal getOrderRebate() {
		return get("order_rebate");
	}

	public void setOrderCommission(java.math.BigDecimal orderCommission) {
		set("order_commission", orderCommission);
	}

	public java.math.BigDecimal getOrderCommission() {
		return get("order_commission");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.String getIsDelete() {
		return get("is_delete");
	}

	public void setFunctions(java.lang.String functions) {
		set("functions", functions);
	}

	public java.lang.String getFunctions() {
		return get("functions");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

}
