<<<<<<< .mine
package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserNo(java.lang.Integer userNo) {
		set("user_no", userNo);
	}

	public java.lang.Integer getUserNo() {
		return get("user_no");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phone_number", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("phone_number");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}

	public java.lang.String getGender() {
		return get("gender");
	}

	public void setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
	}

	public java.lang.String getIdcard() {
		return get("idcard");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setClubId(java.lang.String clubId) {
		set("club_id", clubId);
	}

	public java.lang.String getClubId() {
		return get("club_id");
	}

	public void setImToken(java.lang.String imToken) {
		set("im_token", imToken);
	}

	public java.lang.String getImToken() {
		return get("im_token");
	}

	public void setCardType(java.lang.String cardType) {
		set("card_type", cardType);
	}

	public java.lang.String getCardType() {
		return get("card_type");
	}

}
=======
package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserNo(java.lang.Integer userNo) {
		set("user_no", userNo);
	}

	public java.lang.Integer getUserNo() {
		return get("user_no");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phone_number", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("phone_number");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}

	public java.lang.String getGender() {
		return get("gender");
	}

	public void setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
	}

	public java.lang.String getIdcard() {
		return get("idcard");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setClubId(java.lang.String clubId) {
		set("club_id", clubId);
	}

	public java.lang.String getClubId() {
		return get("club_id");
	}

	public void setCardType(java.lang.String cardType) {
		set("card_type", cardType);
	}

	public java.lang.String getCardType() {
		return get("card_type");
	}

}
>>>>>>> .r2112
