package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRunSubLog<M extends BaseUserRunSubLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setActualMoney(java.math.BigDecimal actualMoney) {
		set("actual_money", actualMoney);
	}

	public java.math.BigDecimal getActualMoney() {
		return get("actual_money");
	}

	public void setRouteMoney(java.math.BigDecimal routeMoney) {
		set("route_money", routeMoney);
	}

	public java.math.BigDecimal getRouteMoney() {
		return get("route_money");
	}

	public void setUserOne(java.lang.String userOne) {
		set("user_one", userOne);
	}

	public java.lang.String getUserOne() {
		return get("user_one");
	}

	public void setUserOneBuddy(java.math.BigDecimal userOneBuddy) {
		set("user_one_buddy", userOneBuddy);
	}

	public java.math.BigDecimal getUserOneBuddy() {
		return get("user_one_buddy");
	}

	public void setUserOneMoeny(java.math.BigDecimal userOneMoeny) {
		set("user_one_moeny", userOneMoeny);
	}

	public java.math.BigDecimal getUserOneMoeny() {
		return get("user_one_moeny");
	}

	public void setUserTow(java.lang.String userTow) {
		set("user_tow", userTow);
	}

	public java.lang.String getUserTow() {
		return get("user_tow");
	}

	public void setUserTowBuddy(java.math.BigDecimal userTowBuddy) {
		set("user_tow_buddy", userTowBuddy);
	}

	public java.math.BigDecimal getUserTowBuddy() {
		return get("user_tow_buddy");
	}

	public void setUserTowMoeny(java.math.BigDecimal userTowMoeny) {
		set("user_tow_moeny", userTowMoeny);
	}

	public java.math.BigDecimal getUserTowMoeny() {
		return get("user_tow_moeny");
	}

	public void setUserThree(java.lang.String userThree) {
		set("user_three", userThree);
	}

	public java.lang.String getUserThree() {
		return get("user_three");
	}

	public void setUserThreeBuddy(java.math.BigDecimal userThreeBuddy) {
		set("user_three_buddy", userThreeBuddy);
	}

	public java.math.BigDecimal getUserThreeBuddy() {
		return get("user_three_buddy");
	}

	public void setUserThreeMoeny(java.math.BigDecimal userThreeMoeny) {
		set("user_three_moeny", userThreeMoeny);
	}

	public java.math.BigDecimal getUserThreeMoeny() {
		return get("user_three_moeny");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.String getIsDelete() {
		return get("is_delete");
	}

}
