package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRouteMag<M extends BaseRouteMag<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setRouteNo(java.lang.Integer routeNo) {
		set("route_no", routeNo);
	}

	public java.lang.Integer getRouteNo() {
		return get("route_no");
	}

	public void setRouteName(java.lang.String routeName) {
		set("route_name", routeName);
	}

	public java.lang.String getRouteName() {
		return get("route_name");
	}

	public void setTravelMode(java.lang.String travelMode) {
		set("travel_mode", travelMode);
	}

	public java.lang.String getTravelMode() {
		return get("travel_mode");
	}

	public void setClubId(java.lang.String clubId) {
		set("club_id", clubId);
	}

	public java.lang.String getClubId() {
		return get("club_id");
	}

	public void setGuideId(java.lang.String guideId) {
		set("guide_id", guideId);
	}

	public java.lang.String getGuideId() {
		return get("guide_id");
	}

	public void setPercentage(java.lang.String percentage) {
		set("percentage", percentage);
	}

	public java.lang.String getPercentage() {
		return get("percentage");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setFeeIncludes(java.lang.String feeIncludes) {
		set("fee_includes", feeIncludes);
	}

	public java.lang.String getFeeIncludes() {
		return get("fee_includes");
	}

	public void setNotIncluded(java.lang.String notIncluded) {
		set("not_included", notIncluded);
	}

	public java.lang.String getNotIncluded() {
		return get("not_included");
	}

	public void setProduct(java.lang.String product) {
		set("product", product);
	}

	public java.lang.String getProduct() {
		return get("product");
	}

	public void setTravelNotes(java.lang.String travelNotes) {
		set("travel_notes", travelNotes);
	}

	public java.lang.String getTravelNotes() {
		return get("travel_notes");
	}

	public void setReducedMobility(java.lang.String reducedMobility) {
		set("reduced_mobility", reducedMobility);
	}

	public java.lang.String getReducedMobility() {
		return get("reduced_mobility");
	}

	public void setTheAged(java.lang.String theAged) {
		set("the_aged", theAged);
	}

	public java.lang.String getTheAged() {
		return get("the_aged");
	}

	public void setMinor(java.lang.String minor) {
		set("minor", minor);
	}

	public java.lang.String getMinor() {
		return get("minor");
	}

	public void setForeignFriends(java.lang.String foreignFriends) {
		set("foreign_friends", foreignFriends);
	}

	public java.lang.String getForeignFriends() {
		return get("foreign_friends");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.String getIsDelete() {
		return get("is_delete");
	}

	public void setSubmitUser(java.lang.String submitUser) {
		set("submit_user", submitUser);
	}

	public java.lang.String getSubmitUser() {
		return get("submit_user");
	}

	public void setVerifyUser(java.lang.String verifyUser) {
		set("verify_user", verifyUser);
	}

	public java.lang.String getVerifyUser() {
		return get("verify_user");
	}

	public void setSubmitTime(java.util.Date submitTime) {
		set("submit_time", submitTime);
	}

	public java.util.Date getSubmitTime() {
		return get("submit_time");
	}

	public void setStartLocation(java.lang.String startLocation) {
		set("start_location", startLocation);
	}

	public java.lang.String getStartLocation() {
		return get("start_location");
	}

	public void setFestival(java.lang.String festival) {
		set("festival", festival);
	}

	public java.lang.String getFestival() {
		return get("festival");
	}

	public void setRefuseMsg(java.lang.String refuseMsg) {
		set("refuse_msg", refuseMsg);
	}

	public java.lang.String getRefuseMsg() {
		return get("refuse_msg");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setNotice(java.lang.String notice) {
		set("notice", notice);
	}

	public java.lang.String getNotice() {
		return get("notice");
	}

	public void setTrafficInfo(java.lang.String trafficInfo) {
		set("traffic_info", trafficInfo);
	}

	public java.lang.String getTrafficInfo() {
		return get("traffic_info");
	}

	public void setPreauthorization(java.lang.String preauthorization) {
		set("preauthorization", preauthorization);
	}

	public java.lang.String getPreauthorization() {
		return get("preauthorization");
	}

	public void setSafetyNotice(java.lang.String safetyNotice) {
		set("safety_notice", safetyNotice);
	}

	public java.lang.String getSafetyNotice() {
		return get("safety_notice");
	}

	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}

	public java.lang.String getThumbnail() {
		return get("thumbnail");
	}

	public void setGoldLimit(java.lang.Integer goldLimit) {
		set("gold_limit", goldLimit);
	}

	public java.lang.Integer getGoldLimit() {
		return get("gold_limit");
	}

	public void setCityId(java.lang.Long cityId) {
		set("city_id", cityId);
	}

	public java.lang.Long getCityId() {
		return get("city_id");
	}

}
