package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTourismClub<M extends BaseTourismClub<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setClubNo(java.lang.Integer clubNo) {
		set("club_no", clubNo);
	}

	public java.lang.Integer getClubNo() {
		return get("club_no");
	}

	public void setClubName(java.lang.String clubName) {
		set("club_name", clubName);
	}

	public java.lang.String getClubName() {
		return get("club_name");
	}

	public void setClubShortName(java.lang.String clubShortName) {
		set("club_short_name", clubShortName);
	}

	public java.lang.String getClubShortName() {
		return get("club_short_name");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return get("avatar");
	}

	public void setBgImg(java.lang.String bgImg) {
		set("bg_img", bgImg);
	}

	public java.lang.String getBgImg() {
		return get("bg_img");
	}

	public void setLegalPerson(java.lang.String legalPerson) {
		set("legal_person", legalPerson);
	}

	public java.lang.String getLegalPerson() {
		return get("legal_person");
	}

	public void setOrganizationCode(java.lang.String organizationCode) {
		set("organization_code", organizationCode);
	}

	public java.lang.String getOrganizationCode() {
		return get("organization_code");
	}

	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

	public java.lang.String getBankName() {
		return get("bank_name");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
	}

	public java.lang.String getBankAccount() {
		return get("bank_account");
	}

	public void setContactPerson(java.lang.String contactPerson) {
		set("contact_person", contactPerson);
	}

	public java.lang.String getContactPerson() {
		return get("contact_person");
	}

	public void setContactPhone(java.lang.String contactPhone) {
		set("contact_phone", contactPhone);
	}

	public java.lang.String getContactPhone() {
		return get("contact_phone");
	}

	public void setProvinceId(java.lang.String provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.String getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.String cityId) {
		set("city_id", cityId);
	}

	public java.lang.String getCityId() {
		return get("city_id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setEnabled(java.lang.String enabled) {
		set("enabled", enabled);
	}

	public java.lang.String getEnabled() {
		return get("enabled");
	}

	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}

	public java.lang.String getIntro() {
		return get("intro");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.String getIsDelete() {
		return get("is_delete");
	}

}
