package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	public void setAccountId(java.lang.String accountId) {
		set("account_id", accountId);
	}

	public java.lang.String getAccountId() {
		return get("account_id");
	}

	public void setAccountNo(java.lang.Long accountNo) {
		set("account_no", accountNo);
	}

	public java.lang.Long getAccountNo() {
		return get("account_no");
	}

	public void setPaymentMode(java.lang.String paymentMode) {
		set("payment_mode", paymentMode);
	}

	public java.lang.String getPaymentMode() {
		return get("payment_mode");
	}

	public void setAccountStatus(java.lang.String accountStatus) {
		set("account_status", accountStatus);
	}

	public java.lang.String getAccountStatus() {
		return get("account_status");
	}

	public void setAccountAmount(java.math.BigDecimal accountAmount) {
		set("account_amount", accountAmount);
	}

	public java.math.BigDecimal getAccountAmount() {
		return get("account_amount");
	}

	public void setClubId(java.lang.String clubId) {
		set("club_id", clubId);
	}

	public java.lang.String getClubId() {
		return get("club_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

}
