package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVipConsumeLog<M extends BaseVipConsumeLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

	public void setGoldBefore(java.lang.Integer goldBefore) {
		set("gold_before", goldBefore);
	}

	public java.lang.Integer getGoldBefore() {
		return get("gold_before");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public void setCashSpend(java.math.BigDecimal cashSpend) {
		set("cash_spend", cashSpend);
	}

	public java.math.BigDecimal getCashSpend() {
		return get("cash_spend");
	}

	public void setCshNum(java.math.BigDecimal cshNum) {
		set("csh_num", cshNum);
	}

	public java.math.BigDecimal getCshNum() {
		return get("csh_num");
	}

	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}

	public java.lang.String getPayType() {
		return get("pay_type");
	}

	public void setConsumeTime(java.util.Date consumeTime) {
		set("consume_time", consumeTime);
	}

	public java.util.Date getConsumeTime() {
		return get("consume_time");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

}
