package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppApphistory<M extends BaseAppApphistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setAppType(java.lang.String appType) {
		set("app_type", appType);
	}

	public java.lang.String getAppType() {
		return get("app_type");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdatePath(java.lang.String updatePath) {
		set("update_path", updatePath);
	}

	public java.lang.String getUpdatePath() {
		return get("update_path");
	}

	public void setUpdateDesc(java.lang.String updateDesc) {
		set("update_desc", updateDesc);
	}

	public java.lang.String getUpdateDesc() {
		return get("update_desc");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setAppVersion(java.lang.String appVersion) {
		set("app_version", appVersion);
	}

	public java.lang.String getAppVersion() {
		return get("app_version");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}

	public java.lang.String getAppName() {
		return get("app_name");
	}

}
