package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setQuota(java.lang.Integer quota) {
		set("quota", quota);
	}

	public java.lang.Integer getQuota() {
		return get("quota");
	}

	public void setGoldReg(java.math.BigDecimal goldReg) {
		set("gold_reg", goldReg);
	}

	public java.math.BigDecimal getGoldReg() {
		return get("gold_reg");
	}

	public void setPointReg(java.lang.Integer pointReg) {
		set("point_reg", pointReg);
	}

	public java.lang.Integer getPointReg() {
		return get("point_reg");
	}

	public void setEnable(java.lang.String enable) {
		set("enable", enable);
	}

	public java.lang.String getEnable() {
		return get("enable");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.String getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}

	public java.lang.String getTarget() {
		return get("target");
	}

	public void setGoldLogin(java.math.BigDecimal goldLogin) {
		set("gold_login", goldLogin);
	}

	public java.math.BigDecimal getGoldLogin() {
		return get("gold_login");
	}

	public void setPointLogin(java.lang.Integer pointLogin) {
		set("point_login", pointLogin);
	}

	public java.lang.Integer getPointLogin() {
		return get("point_login");
	}

}
