package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLocationRecord<M extends BaseLocationRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

	public void setSpeed(java.lang.Float speed) {
		set("speed", speed);
	}

	public java.lang.Float getSpeed() {
		return get("speed");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setImei(java.lang.String imei) {
		set("imei", imei);
	}

	public java.lang.String getImei() {
		return get("imei");
	}

}
