package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseItinerary<M extends BaseItinerary<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMorning(java.lang.String morning) {
		set("morning", morning);
	}

	public java.lang.String getMorning() {
		return get("morning");
	}

	public void setNoon(java.lang.String noon) {
		set("noon", noon);
	}

	public java.lang.String getNoon() {
		return get("noon");
	}

	public void setAtNight(java.lang.String atNight) {
		set("at_night", atNight);
	}

	public java.lang.String getAtNight() {
		return get("at_night");
	}

	public void setLodging(java.lang.String lodging) {
		set("lodging", lodging);
	}

	public java.lang.String getLodging() {
		return get("lodging");
	}

	public void setTraffic(java.lang.String traffic) {
		set("traffic", traffic);
	}

	public java.lang.String getTraffic() {
		return get("traffic");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setOrderBy(java.lang.Integer orderBy) {
		set("order_by", orderBy);
	}

	public java.lang.Integer getOrderBy() {
		return get("order_by");
	}

	public void setRouteId(java.lang.String routeId) {
		set("route_id", routeId);
	}

	public java.lang.String getRouteId() {
		return get("route_id");
	}

	public void setDetailTitle(java.lang.String detailTitle) {
		set("detail_title", detailTitle);
	}

	public java.lang.String getDetailTitle() {
		return get("detail_title");
	}

}
