package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSet<M extends BaseSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setChatState(java.lang.String chatState) {
		set("chat_state", chatState);
	}

	public java.lang.String getChatState() {
		return get("chat_state");
	}

	public void setAttraState(java.lang.String attraState) {
		set("attra_state", attraState);
	}

	public java.lang.String getAttraState() {
		return get("attra_state");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

}
