package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayLog<M extends BasePayLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}

	public java.lang.String getPayType() {
		return get("pay_type");
	}

	public void setFeeGold(java.math.BigDecimal feeGold) {
		set("fee_gold", feeGold);
	}

	public java.math.BigDecimal getFeeGold() {
		return get("fee_gold");
	}

	public void setFeeCash(java.math.BigDecimal feeCash) {
		set("fee_cash", feeCash);
	}

	public java.math.BigDecimal getFeeCash() {
		return get("fee_cash");
	}

	public void setTppUserId(java.lang.String tppUserId) {
		set("tpp_user_id", tppUserId);
	}

	public java.lang.String getTppUserId() {
		return get("tpp_user_id");
	}

	public void setPayStatus(java.lang.String payStatus) {
		set("pay_status", payStatus);
	}

	public java.lang.String getPayStatus() {
		return get("pay_status");
	}

	public void setTtpErrorCode(java.lang.String ttpErrorCode) {
		set("ttp_error_code", ttpErrorCode);
	}

	public java.lang.String getTtpErrorCode() {
		return get("ttp_error_code");
	}

	public void setTppTradeNo(java.lang.String tppTradeNo) {
		set("tpp_trade_no", tppTradeNo);
	}

	public java.lang.String getTppTradeNo() {
		return get("tpp_trade_no");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setOperation(java.lang.String operation) {
		set("operation", operation);
	}

	public java.lang.String getOperation() {
		return get("operation");
	}

}
