package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTagLine<M extends BaseTagLine<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTagId(java.lang.String tagId) {
		set("tag_id", tagId);
	}

	public java.lang.String getTagId() {
		return get("tag_id");
	}

	public void setLineId(java.lang.String lineId) {
		set("line_Id", lineId);
	}

	public java.lang.String getLineId() {
		return get("line_Id");
	}

}
