package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSendLog<M extends BaseSendLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setPublicId(java.lang.String publicId) {
		set("public_id", publicId);
	}

	public java.lang.String getPublicId() {
		return get("public_id");
	}

	public void setSendStatus(java.lang.String sendStatus) {
		set("send_status", sendStatus);
	}

	public java.lang.String getSendStatus() {
		return get("send_status");
	}

	public void setSendType(java.lang.String sendType) {
		set("send_type", sendType);
	}

	public java.lang.String getSendType() {
		return get("send_type");
	}

	public void setRedNum(java.lang.Integer redNum) {
		set("red_num", redNum);
	}

	public java.lang.Integer getRedNum() {
		return get("red_num");
	}

	public void setLikeNum(java.lang.Integer likeNum) {
		set("like_num", likeNum);
	}

	public java.lang.Integer getLikeNum() {
		return get("like_num");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.String getIsDelete() {
		return get("is_delete");
	}

}
