package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChatGroupRecord<M extends BaseChatGroupRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setGroupId(java.lang.String groupId) {
		set("group_id", groupId);
	}

	public java.lang.String getGroupId() {
		return get("group_id");
	}

	public void setPosterId(java.lang.String posterId) {
		set("poster_id", posterId);
	}

	public java.lang.String getPosterId() {
		return get("poster_id");
	}

	public void setMsgType(java.lang.String msgType) {
		set("msg_type", msgType);
	}

	public java.lang.String getMsgType() {
		return get("msg_type");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setIsDeleted(java.lang.String isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.String getIsDeleted() {
		return get("is_deleted");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setTtpId(java.lang.String ttpId) {
		set("ttp_id", ttpId);
	}

	public java.lang.String getTtpId() {
		return get("ttp_id");
	}

}
