package com.lvoutcity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperationLog<M extends BaseOperationLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTargetType(java.lang.Integer targetType) {
		set("target_type", targetType);
	}

	public java.lang.Integer getTargetType() {
		return get("target_type");
	}

	public void setTargetId(java.lang.String targetId) {
		set("target_id", targetId);
	}

	public java.lang.String getTargetId() {
		return get("target_id");
	}

	public void setOperType(java.lang.Integer operType) {
		set("oper_type", operType);
	}

	public java.lang.Integer getOperType() {
		return get("oper_type");
	}

	public void setOperUser(java.lang.String operUser) {
		set("oper_user", operUser);
	}

	public java.lang.String getOperUser() {
		return get("oper_user");
	}

	public void setOperTime(java.util.Date operTime) {
		set("oper_time", operTime);
	}

	public java.util.Date getOperTime() {
		return get("oper_time");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

}
