package com.lvoutcity.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_account", "account_id", Account.class);
		arp.addMapping("t_activity", "id", Activity.class);
		arp.addMapping("t_app_apphistory", "id", AppApphistory.class);
		arp.addMapping("t_app_login_img", "id", AppLoginImg.class);
		arp.addMapping("t_area", "id", Area.class);
		arp.addMapping("t_attention", "id", Attention.class);
		arp.addMapping("t_attention_history", "id", AttentionHistory.class);
		arp.addMapping("t_attractions", "id", Attractions.class);
		arp.addMapping("t_chat_group", "id", ChatGroup.class);
		arp.addMapping("t_chat_group_user", "id", ChatGroupUser.class);
		arp.addMapping("t_corps", "id", Corps.class);
		arp.addMapping("t_corps_leader", "id", CorpsLeader.class);
		arp.addMapping("t_data_dictionary", "id", DataDictionary.class);
		arp.addMapping("t_data_dictionary_type", "id", DataDictionaryType.class);
		arp.addMapping("t_feedback", "id", Feedback.class);
		arp.addMapping("t_friend", "id", Friend.class);
		arp.addMapping("t_friends_req", "id", FriendsReq.class);
		arp.addMapping("t_guide", "id", Guide.class);
		arp.addMapping("t_guide_marker_line", "id", GuideMarkerLine.class);
		arp.addMapping("t_hot_city", "id", HotCity.class);
		arp.addMapping("t_itinerary", "id", Itinerary.class);
		arp.addMapping("t_map_poly_line_data", "id", MapPolyLineData.class);
		arp.addMapping("t_map_raiders", "id", MapRaiders.class);
		arp.addMapping("t_no_public", "id", NoPublic.class);
		arp.addMapping("t_order_function", "id", OrderFunction.class);
		arp.addMapping("t_order_record", "id", OrderRecord.class);
		// Composite Primary Key order: date_time,route_id
		arp.addMapping("t_page_view", "date_time,route_id", PageView.class);
		arp.addMapping("t_pay_log", "id", PayLog.class);
		arp.addMapping("t_picture_group", "id", PictureGroup.class);
		arp.addMapping("t_picture_list", "id", PictureList.class);
		arp.addMapping("t_protocol", "id", Protocol.class);
		arp.addMapping("t_role_menu", "id", RoleMenu.class);
		arp.addMapping("t_route_img", "id", RouteImg.class);
		arp.addMapping("t_route_mag", "id", RouteMag.class);
		arp.addMapping("t_set", "id", Set.class);
		arp.addMapping("t_sys_menu", "id", SysMenu.class);
		arp.addMapping("t_sys_role", "id", SysRole.class);
		arp.addMapping("t_tag_line", "id", TagLine.class);
		arp.addMapping("t_tag_mag", "id", TagMag.class);
		arp.addMapping("t_tourism_club", "id", TourismClub.class);
		arp.addMapping("t_tourist_info", "id", TouristInfo.class);
		arp.addMapping("t_travelogue", "id", Travelogue.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_user_backgroup", "id", UserBackgroup.class);
		arp.addMapping("t_user_member", "id", UserMember.class);
		arp.addMapping("t_user_opt_log", "id", UserOptLog.class);
		arp.addMapping("t_user_role", "id", UserRole.class);
		arp.addMapping("t_user_run_sub_log", "id", UserRunSubLog.class);
		arp.addMapping("t_user_wallet", "id", UserWallet.class);
		arp.addMapping("t_wallet", "id", Wallet.class);
	}
}

