package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseAppApphistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppApphistory extends BaseAppApphistory<AppApphistory> {
	public static final AppApphistory dao = new AppApphistory();
	
	public AppApphistory getApp(String type){
		return AppApphistory.dao.findFirst("select * from t_app_apphistory  where app_type ='"+type+"' order by update_time desc  limit 0, 1 ");
	}
}
