package com.lvoutcity.model;

import java.util.ArrayList;
import java.util.List;

import com.lvoutcity.model.base.BaseAppLoginImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppLoginImg extends BaseAppLoginImg<AppLoginImg> {
	public static final AppLoginImg dao = new AppLoginImg();
	public static List<String> allPictureUrl(){
		List<AppLoginImg> imgs = dao.find("select * from t_app_login_img order by create_time");
		List<String> urls = new ArrayList<String>();
		imgs.forEach(i-> urls.add(i.getUrl()));
		return urls;
	}
	public List<AppLoginImg> getLogin(){
		return AppLoginImg.dao.find("select * from t_app_login_img ");
	}
	
	/**
	 * 
	 * @param type
	 * @param pictureSize
	 * @return
	 */
	public AppLoginImg queryLoginInfo(String type){
		return AppLoginImg.dao.findFirst("select  * from t_app_login_img where app_type='"+type+"' order by rand()  limit 1"); 
	}

}
