package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseAttentionHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttentionHistory extends BaseAttentionHistory<AttentionHistory> {
	public static final AttentionHistory dao = new AttentionHistory();
	
	 public AttentionHistory findHistory(String sql){
	    	return AttentionHistory.dao.findFirst("select * from t_attention_history "+sql);
		}
	 
	 /**
	  * 
	  * @Title: queryAttentionHistoryList 
	  * @Description: 查询用户转发数据
	  * @param @return    设定文件 
	  * @return List<AttentionHistory>    返回类型 
	  * @create_time 2016 2016年7月8日 下午4:27:36
	  * @create_user James w.s
	  * @throws
	  */
	 public List<AttentionHistory> queryAttentionHistoryList(String userId,String routeNo){
		 return dao.find("select * from t_attention_history ah where ah.user_id='"+userId+"' and ah.route_no='"+routeNo+"'");
	 }
}
