package com.lvoutcity.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.lvoutcity.model.base.BaseChatGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatGroup extends BaseChatGroup<ChatGroup> {
	public static final ChatGroup dao = new ChatGroup();
	Boolean shareLocation;
	public Boolean getShareLocation() {
		return shareLocation;
	}
	public void setShareLocation(Boolean shareLocation) {
		this.shareLocation = shareLocation;
	}

	/**
	 * 获取当前群组的前9名用户头像
	 * @return
	 */
	public List<String> topNineAvatar(){
		List<String> aList = new ArrayList<String>();
		List<Record> lr = Db.find("select avatar "
				+ "from t_chat_group cg left join t_chat_group_user cgu on cgu.group_id=cg.id "
				+ "left join t_user_member um on cgu.user_Id=um.user_id "
				+ "where cg.id = '"+getId()+"' order by cgu.create_time limit 9");
		lr.forEach(r->{
			if(r.get("avatar")!=null)
				aList.add(r.get("avatar"));
		});
		return aList;
	}
	
	/**
	 * 是否需要新的头像
	 * @return
	 */
	public boolean needNewAvatar(String userId){
		if(userId==null){
			Record r = Db.findFirst("select count(1) as count from t_chat_group_user where group_id='"+getId()+"' order by create_time");
			return Integer.valueOf(r.get("count").toString())<9;
		}else{
			List<Record> r = Db.find("select * from (select user_id  from t_chat_group_user where group_id='"+getId()+"' order by create_time limit 9) t where user_id='"+userId+"'");
			return r.size()>0;
		}
	}
	
	
	/**
	 * 如果成员为0则删除本记录
	 */
	public boolean deleteIfNeed(){
//		if(getSystemGroup().equals("1"))
//			return false;
		Record r = Db.findFirst("select count(1) as count from t_chat_group_user where group_id='"+getId()+"'");
		if(Integer.valueOf(r.get("count").toString()).equals(0)){
			delete();
			return true;
		}else{
			return false;
		}
	}
}
