package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseDataDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionary extends BaseDataDictionary<DataDictionary> {
	public static final DataDictionary dao = new DataDictionary();
	
	private String tCode;

	public String gettCode() {
		return tCode;
	}

	public void settCode(String tCode) {
		this.tCode = tCode;
	}
}
