package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseDataDictionaryType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionaryType extends BaseDataDictionaryType<DataDictionaryType> {
	public static final DataDictionaryType dao = new DataDictionaryType();
}
