package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseFriendsReq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendsReq extends BaseFriendsReq<FriendsReq> {
	public static final FriendsReq dao = new FriendsReq();
	
	/**
	 * 获取好友申请列表
	 * 别人申请我的
	 * @param userId
	 * @return
	 */
	public List<FriendsReq> getFriendApply(String userId){
		return FriendsReq.dao.find("select * from t_friends_req where aimed_id ='"+userId+"' and requestState in('0','2')");
	}
	
	/**
	 * 获取好友申请列表
	 * 我申请别人的
	 * @param userId
	 * @return
	 */
	public List<FriendsReq>  queryFriendApply(String userId){
		return FriendsReq.dao.find("select * from t_friends_req where user_id='"+userId+"' and requestState in('0','2')");
	}
	
	public List<FriendsReq> getMyApply(String userId){
		return FriendsReq.dao.find("select * from t_friends_req where user_id ='"+userId+"'");
	}
	
	
	/**
	 * 根据条件获取申请信息 ---判断是否已申请
	 * @param userid
	 * @param frindid
	 * @return
	 */
	public FriendsReq getFriendsReq(String userid,String frindid){
		return FriendsReq.dao.findFirst("select * from t_friends_req where user_id ='"+userid +"' and aimed_id='"+frindid+"'");
	}
	
	public FriendsReq queryFriendsReq(int lvNo,String userId){
		return FriendsReq.dao.findFirst("select req.* from t_friends_req as req "
				+ "left join t_user as user on user.id = req.aimed_id where user.user_no="+lvNo+" and req.user_id='"+userId+"'");
	}
}
