package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseGuide;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Guide extends BaseGuide<Guide> {
	public static final Guide dao = new Guide();
	
	public Guide findByNo(String no){
		return dao.findFirst("select * from t_guide where enabled = 1 and guide_no = '"+no+"'");
	}
	

	public Guide findByNoAndClub(String no,String clubId){
		return dao.findFirst("select * from t_guide where enabled = 1 and guide_no = '"+no+"' and  club_id = '"+clubId+"'");
	}
	
	public Guide findByClubId(String clubId){
		return dao.findFirst("select * from t_guide where enabled = 1 and club_id = '"+clubId+"'");
	}
	
	private String copyData;				//复制数据
	
	public String getCopyData() {
		return copyData;
	}

	public void setCopyData(String copyData) {
		this.copyData = copyData;
	}

	public int dayCount(){
		int duration = Integer.valueOf(getDuration());
		int night = Integer.valueOf(getNight());
		int dayCount = duration>night?duration:night;
		return dayCount;
	}
}
