package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseGuideMarkerLine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GuideMarkerLine extends BaseGuideMarkerLine<GuideMarkerLine> {
	public static final GuideMarkerLine dao = new GuideMarkerLine();
	
	/**
	 * 获取地图
	 * @param guideId
	 * @return
	 */
	public GuideMarkerLine queryGuideMarkerLine(String guideId){
		return GuideMarkerLine.dao.findFirst("select * from t_guide_marker_line where guide_id='"+guideId+"'");
	}
}
