package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseHotCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotCity extends BaseHotCity<HotCity> {
	public static final HotCity dao = new HotCity();
	public List<HotCity> getCity(String isHot){
		return HotCity.dao.find("select id,h_name from t_hot_city where is_hot = "+ isHot+" and is_delete = 1");
	}
	
}
