package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseItinerary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Itinerary extends BaseItinerary<Itinerary> {
	public static final Itinerary dao = new Itinerary();
	
	public List<Itinerary> findByRouteId(String id){
		return Itinerary.dao.find("select * from t_itinerary  where route_id = '"+id+"' order by order_by");
	}
	public Itinerary findItinerary(String routeId){
		return Itinerary.dao.findFirst("select * from t_itinerary where route_id = '"+routeId+"'");
	};
}
