package com.lvoutcity.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.lvoutcity.core.util.LvoutcityUtils;
import com.lvoutcity.core.util.SQuery;
import com.lvoutcity.model.base.BaseMapPolyLineData;

/**
 * Generated by JFinal.
 */
/**
 * @author wss
 *
 */
@SuppressWarnings("serial")
public class MapPolyLineData extends BaseMapPolyLineData<MapPolyLineData> {
	public static final MapPolyLineData dao = new MapPolyLineData();

	public void updateCityData(String id, String[] cities) {
		
		Db.update("delete from t_map_poly_line_data where guide_id='"+id+"'");
		if(cities!=null)
			for(int i=0, length=cities.length;i<length;i++){
				String[] c = cities[i].split("-");
				MapPolyLineData m = new MapPolyLineData();
				m.setId(LvoutcityUtils.getUUID());
				m.setProvince(c[0]);
				m.setCity(c[1]);
				m.setGuideId(id);
				m.save();
			}
		
	}

	
	/**
	 * find cities info of guide
	 * @param guideId
	 * @return
	 */
	public MapPolyLineData queryMapPolyLine(String guideId){
		SQuery find = SQuery.create("select * from t_map_poly_line_data m where 1=1 ");

		find.append(" and m.guide_id = '"+guideId+"'");
		return MapPolyLineData.dao.findFirst(find.getSQuery());
	}
	public List<String> findByGuideId(String id){
		List<String> l  = new ArrayList<String>();
		List<MapPolyLineData> ril = dao.find("select * from t_map_poly_line_data where guide_id='"+id+"'");
		ril.forEach(ri->l.add(ri.getProvince()+"-"+ri.getCity()));
		return l;
	}
}
