package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.core.util.LvoutcityUtils;
import com.lvoutcity.core.util.SQuery;
import com.lvoutcity.model.base.BaseMapRaiders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MapRaiders extends BaseMapRaiders<MapRaiders> {
	public static final MapRaiders dao = new MapRaiders();
	
	public String lng;
	
	public String lat;

	public String superMapId;
	
	public Integer count;
	
	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getSuperMapId() {
		return superMapId;
	}

	public void setSuperMapId(String superMapId) {
		this.superMapId = superMapId;
	}

	public String getLng() {
		return lng;
	}

	public void setLng(String lng) {
		this.lng = lng;
	}

	public String getLat() {
		return lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}
	
	public List<MapRaiders> queryMapRaidersList(String guideId){
		SQuery find = SQuery.create("select * from t_map_raiders m where m.is_delete = 1");
		find.append(" and m.status = 1 ");

		find.append(" and m.guide_id = '"+guideId+"'");
		return MapRaiders.dao.find(find.getSQuery());
	}
	
	
	
	/**
	 * 
	 * @Title: getMapRaidersList 
	 * @Description: 返回变成总数
	 * @param @return    设定文件 
	 * @return Integer    返回类型 
	 * @create_time 2016下午5:06:15
	 * @create_user James w.s
	 * @throws
	 */
	public Integer getMapRaidersCount(String id){
		SQuery find = SQuery.create("select count(1) as count from t_map_raiders m where m.is_delete = 1");
		find.append(" and m.status = '"+id+"'");
		MapRaiders s = MapRaiders.dao.findFirst(find.getSQuery());
		return LvoutcityUtils.isNotNull(s.getCount()) ? s.getCount() : 1;
	}
}
