package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseNoPublic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoPublic extends BaseNoPublic<NoPublic> {
	public static final NoPublic dao = new NoPublic();
}
