package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseOrderFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderFunction extends BaseOrderFunction<OrderFunction> {
	public static final OrderFunction dao = new OrderFunction();
}
