package com.lvoutcity.model;

import com.lvoutcity.model.base.BasePageView;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PageView extends BasePageView<PageView> {
	public static final PageView dao = new PageView();
}
