package com.lvoutcity.model;

import com.lvoutcity.core.util.LvoutcityUtils;
import com.lvoutcity.model.base.BasePayLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayLog extends BasePayLog<PayLog> {
	public static final PayLog dao = new PayLog();
	
	/**
	 * @param ord 订单
	 * @param type 支付宝|微信|金币
	 * @param status 成功|失败
	 * @return
	 */
	public PayLog buildLog(OrderRecord ord, String type, String status){
		PayLog pl = new PayLog();
		pl.setId(LvoutcityUtils.getUUID());
		pl.setCreateUser(ord.getCreateUser());
		pl.setFeeCash(ord.getFeeCash());
		pl.setFeeGold(ord.getFeeGold());
		pl.setOrderId(ord.getId());
		pl.setPayType(type);
		pl.setPayStatus(status);
		return pl;
	}
}
