package com.lvoutcity.model;

import com.lvoutcity.model.base.BasePictureGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PictureGroup extends BasePictureGroup<PictureGroup> {
	public static final PictureGroup dao = new PictureGroup();
}
