package com.lvoutcity.model;

import com.lvoutcity.model.base.BasePictureList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PictureList extends BasePictureList<PictureList> {
	public static final PictureList dao = new PictureList();
}
