package com.lvoutcity.model;

import com.lvoutcity.core.util.LvoutcityUtils;
import com.lvoutcity.model.base.BaseProtocol;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Protocol extends BaseProtocol<Protocol> {
	public static final Protocol dao = new Protocol();
	
	public static Protocol instance(){   
		Protocol p = dao.findFirst("select * from t_protocol");
		if(p==null){
			p = new Protocol();
			p.setId(LvoutcityUtils.getUUID());
			p.save();
		}
		return p;
	}

	/**
	 * 
	 * @Title: queryProtocol 
	 * @Description: 分润方式
	 * @param @return    设定文件 
	 * @return Protocol    返回类型 
	 * @create_time 2016上午11:53:26
	 * @create_user James w.s
	 * @throws
	 */
	public Protocol queryProtocol() {
		return dao.findFirst("select * from t_protocol ");
	}
	
	/**
	 * 获取登陆时持续时间
	 * @param 
	 * @return
	 */
	
	public Protocol queryAppLoginTime(){
		return Protocol.dao.findFirst("select * from t_protocol  order by update_time desc  limit 0, 1 ");
	}
}
