package com.lvoutcity.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.lvoutcity.model.base.BaseRouteImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RouteImg extends BaseRouteImg<RouteImg> {
	public static final RouteImg dao = new RouteImg();
	
	public void removeAllImg(String id){
		Db.update("delete from t_route_img where route_id='"+id+"'");
	}
	
	public List<String> findUrlByRouteId(String id){
		List<String> l  = new ArrayList<String>();
		List<RouteImg> ril = dao.find("select * from t_route_img where route_id='"+id+"'");
		ril.forEach(ri->l.add(ri.getUrl()));
		return l;
	}
	
	
}
