package com.lvoutcity.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.lvoutcity.core.util.Constants;
import com.lvoutcity.core.util.HuiUtils;
import com.lvoutcity.core.util.SQuery;
import com.lvoutcity.core.util.ZTree;
import com.lvoutcity.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu();
	
	private String superName;

	public String getSuperName() {
		return superName;
	}

	public void setSuperName(String superName) {
		this.superName = superName;
	}
	

	/**
	 * 
	 * @Title: querySysMenu 
	 * @Description: 获取所有菜单 
	 * @param     设定文件 
	 * @return void    返回类型 
	 * @create_time 2016上午10:26:54
	 * @create_user James w.s
	 * @throws
	 */
	public void querySysMenu(){
		
	}

	/**
	 * 
	 * @Title: queryAllMenuTreeNode 
	 * @Description: 获取所有菜单节点
	 * @param @param user
	 * @param @return    设定文件 
	 * @return List<ZTree>    返回类型 
	 * @create_time 2016下午3:37:13
	 * @create_user James w.s
	 * @throws
	 */
	public List<ZTree> queryAllMenuTreeNode(User user) {
		SQuery sql = SQuery.create("select * from t_sys_menu m where m.is_delete = 1 and m.role_menu is null and enabled is null order by m.order_by asc  ");
		List<SysMenu> list = dao.find(sql.getSQuery());
		List<ZTree> zTree = new ArrayList<ZTree>();
		for(SysMenu sm : list){
			ZTree z = new ZTree(sm.getId(),sm.getName(),sm.getSuperId(),sm.getMenuUrl(),sm.getRoleMenu(),sm.getIconCls());
			zTree.add(z);
		}
		return HuiUtils.toTreeList(zTree, Constants.TOP_LEVEL_MENU);
	}

	/**
	 * 
	 * @Title: getPermissionRoles 
	 * @Description: init botton user
	 * @param @param user
	 * @param @return    设定文件 
	 * @return Map<String,List<SysMenu>>    返回类型 
	 * @create_time 2016下午3:53:53
	 * @create_user James w.s
	 * @throws
	 */
	public Map<String, List<SysMenu>> getPermissionRoles(User user) {//and m.enabled = 1
		SQuery sql = SQuery.create("select * from t_sys_menu m  where m.is_delete =1 and m.role_menu is not null and m.id in ( ");
		sql.append(" select distinct(rm.menu_id) from t_role_menu rm where rm.role_id in (  ");
		sql.append(" select role_id from t_user_role ur where ur.user_id ='"+user.getId()+"'");
		sql.append(" )");
		sql.append(" )");
		sql.append(" order by m.order_by asc ");
		List<SysMenu> list = dao.find(sql.getSQuery());
		Map<String,List<SysMenu>> map = new HashMap<String, List<SysMenu>>();
		for(SysMenu menu : list){
			if(!map.containsKey(menu.getOrderType())){
				List<SysMenu> oList = new ArrayList<SysMenu>();
				oList.add(menu);
				map.put(menu.getOrderType(), oList);
			}
			else{
				map.get(menu.getOrderType()).add(menu);
			}
		}
		return map;
	}

	/**
	 * 
	 * @Title: getPermissionMenuTreeNode 
	 * @Description: TODO(这里用一句话描述这个方法的作用) 
	 * @param @param user
	 * @param @return    设定文件 
	 * @return List<ZTree>    返回类型 
	 * @create_time 2016下午3:54:14
	 * @create_user James w.s
	 * @throws
	 */
	public List<ZTree> getPermissionMenuTreeNode(User user) {
		SQuery sql = SQuery.create("select * from t_sys_menu m  where m.is_delete =1  and m.enabled is null  and m.role_menu is null and m.id in ( ");
		sql.append(" select distinct(rm.menu_id) from t_role_menu rm where rm.role_id in (  ");
		sql.append(" select role_id from t_user_role ur where ur.user_id ='"+user.getId()+"'");
		sql.append(" )");
		sql.append(" )");
		sql.append(" order by m.order_by asc");
		List<SysMenu> list = dao.find(sql.getSQuery());
		List<ZTree> zTree = new ArrayList<ZTree>();
		for(SysMenu sm : list){
			ZTree z = new ZTree(sm.getId(),sm.getName(),sm.getSuperId(),sm.getMenuUrl(),sm.getRoleMenu(),sm.getIconCls());
			zTree.add(z);
		}
		return HuiUtils.toTreeList(zTree, Constants.TOP_LEVEL_MENU);
	}
}
