package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseTagLine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TagLine extends BaseTagLine<TagLine> {
	public static final TagLine dao = new TagLine();
}
