package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseTagMag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TagMag extends BaseTagMag<TagMag> {
	public static final TagMag dao = new TagMag();
	
	public  List<TagMag> findByLineId(String lineId){
		return TagMag.dao.find("select tm.* from t_tag_mag tm left join t_tag_line tl on (tm.id=tl.tag_id) where tm.is_delete != 0 and tl.line_id = '"+lineId+"'");
	}
}
