package com.lvoutcity.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.lvoutcity.model.base.BaseTouristInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TouristInfo extends BaseTouristInfo<TouristInfo> {
	public static final TouristInfo dao = new TouristInfo();
	
	/**
	 * 移除取消订单的游客信息
	 * @param orderId
	 */
	public void cancelTourist(String orderId){
		Db.update("update t_tourist_info set is_delete='0' where order_id = '"+orderId+"'");
	}
	
	public long countTouristsByClub(String id){
		String sql = "select count(1) as count from " + "t_tourist_info ti left join t_corps c on ti.corps_id=c.id "
				+ "left join t_route_mag rm on rm.id = c.route_id ";
		if (id != null)
			sql += "where rm.club_id='" + id + "'";
		Record tourists = Db.findFirst(sql);
		return tourists.get("count");
	}
}
