package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseTourismClub;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TourismClub extends BaseTourismClub<TourismClub> {
	public static final TourismClub dao = new TourismClub();
	
	public TourismClub findByClubId(String id){
		return TourismClub.dao.findById(id);
	}
	
	
	
	/**
	 * 
	 * @Title: getTourismClubList 
	 * @Description: 查询所有俱乐部 
	 * @param @return    设定文件 
	 * @return List<TourismClub>    返回类型 
	 * @create_time 2016下午7:08:31
	 * @create_user James w.s
	 * @throws
	 */
	public List<TourismClub> queryTourismClubList(){
		return TourismClub.dao.find("select * from t_tourism_club where enabled ='1' and is_delete='1' ");
	}
}
