package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseTravelogue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Travelogue extends BaseTravelogue<Travelogue> {
	public static final Travelogue dao = new Travelogue();
}
