package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseUserRunSubLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRunSubLog extends BaseUserRunSubLog<UserRunSubLog> {
	public static final UserRunSubLog dao = new UserRunSubLog();
}
