package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public User findByPhoneNumber(String phoneNumber) {
		return User.dao.findFirst(
				"select * from t_user  where phone_number=?",
				phoneNumber);
	}
	/**
	 * 模糊查询
	 * @param lvNo
	 * @return
	 */
	public List<User> findByLvNo(String lvNo) {
		return User.dao.find(
				"select * from t_user  where user_no like  '"+lvNo +"'");
	}
	
	
	public User getInfoBylvNo(int lvNo){
		return User.dao.findFirst("select * from t_user where user_no ="+lvNo);
	}
	
	
	private String roleIds;			//权限管理id
	
	private String roleName;			//权限名称
	
	private String status;			//用户当前状态
	
	private String password;		//用户密码
	
	private String userName;		//用户登录账号
	
	/**
	 * 根据手机号精确搜索索要添加的联系人
	 * @param phone
	 * @return
	 */
	public User getUsersById(String userId,String friendId ){
		return 	User.dao.findFirst("select user.nick_name as nick_name,user.user_no as user_no, friend.avatar as avatar,member   "
				+ "from  t_user as user left join t_friend as friend "
				+ "ON `user`.id = friend.friend_id");
	}
	
	
	/**
	 * 
	 * @Title: getUserId 
	 * @Description: 根据user_id 查询user _back数据信息
	 * @param @return    设定文件 
	 * @return UserBackgroup    返回类型 
	 * @create_time 2016下午4:57:19
	 * @create_user James w.s
	 * @throws
	 */
	public UserBackgroup queryUserId(String id ){
		return UserBackgroup.dao.findFirst("select * from t_user_backgroup g  where is_delete='1' and  g.user_id = '"+id+"'");
	}
	
	
	public String getRoleName() {
		return roleName;
	}
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	
	public String getRoleIds() {
		return roleIds;
	}
	public void setRoleIds(String roleIds) {
		this.roleIds = roleIds;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return get("avatar");
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	
}
