package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseUserOptLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOptLog extends BaseUserOptLog<UserOptLog> {
	public static final UserOptLog dao = new UserOptLog();
}
