package com.lvoutcity.model;

import com.lvoutcity.model.base.BaseUserBackgroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBackgroup extends BaseUserBackgroup<UserBackgroup> {
	public static final UserBackgroup dao = new UserBackgroup();
	
	/**
	 * 验证码
	 */
	private String vaildCode ;

	public String getVaildCode() {
		return vaildCode;
	}

	public void setVaildCode(String vaildCode) {
		this.vaildCode = vaildCode;
	}
	
	public UserBackgroup findByUserId(String userId){
		return findFirst("select * from t_user_backgroup where user_id = '"+userId+"'");
	}
	
	
}
