package com.lvoutcity.model;

import java.util.List;

import com.lvoutcity.model.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole();
	
	/**
	 * 
	 * @Title: queryUserRoleList 
	 * @Description: TODO(这里用一句话描述这个方法的作用) 
	 * @param     设定文件 
	 * @return void    返回类型 
	 * @create_time 2016上午10:44:20
	 * @create_user James w.s
	 * @throws
	 */
	public List<UserRole> queryUserRoleList(String userId){
		return dao.find(" select u.role_id from t_user_role u where u.user_id ='"+userId+"'");
	}
}
